import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "AI Interview Schedule Voice Agent",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "AI Interview Schedule Voice Agent",
  description: "Generated by create next app",
  metadataBase: new URL("https://prepslay.vercel.app"),
  openGraph: {
    title: "AI Interview Schedule Voice Agent – Prepslay",
    description: "Your smart assistant for scheduling interviews using AI voice tech.",
    url: "https://prepslay.vercel.app",
    siteName: "Prepslay",
    images: [
      {
        url: "/meta.png",
        width: 1200,
        height: 630,
        alt: "Prepslay – AI Interview Scheduler",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Interview Schedule Voice Agent – Prepslay",
    description: "Your smart assistant for scheduling interviews using AI voice tech.",
    site: "@prepslay", // optional – only if you have a Twitter handle
    images: ["/meta.png"],
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
